<?php
declare(strict_types=1);
$config=require '/home/isplzepc/gptreseller-app/config/config.php';
if(session_status()!==PHP_SESSION_ACTIVE){session_name($config['session_name']);session_start();}
$db=new PDO('mysql:host='.$config['db']['host'].';dbname='.$config['db']['name'].';charset=utf8mb4',$config['db']['user'],$config['db']['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function login():array{if(empty($_SESSION['user'])){header('Location:index.php?page=login');exit;}return $_SESSION['user'];}
function api(array $o,string $module,string $method='GET',array $p=[]):array{
 $host=(string)$o['host'];$port=(int)($o['web_port']??9092);$scheme=(($o['web_scheme']??'http')==='https'?'https':'http');$path=(string)($o['web_base_path']??'/cgi-bin/h.cgi');$base=$scheme.'://'.$host.':'.$port.$path;
 $cookie=tempnam(sys_get_temp_dir(),'ecom');$url=$base.'?'.http_build_query(array_merge(['module'=>$module],$method==='GET'?$p:[]));$c=curl_init($url);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>6,CURLOPT_TIMEOUT=>20,CURLOPT_COOKIEJAR=>$cookie,CURLOPT_COOKIEFILE=>$cookie,CURLOPT_HTTPHEADER=>['Accept: application/json, text/plain, */*','User-Agent: ECOM-CGI-Monitor/1.0']]);
 if($method==='POST'){curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,http_build_query($p));}
 $body=curl_exec($c);$err=curl_error($c);$code=(int)curl_getinfo($c,CURLINFO_HTTP_CODE);curl_close($c);@unlink($cookie);if($body===false)throw new RuntimeException($err);return['http'=>$code,'raw'=>(string)$body,'json'=>json_decode((string)$body,true)];
}
function call(array $o,string $module,string $method,array $p):array{
 $pass=base64_decode((string)$o['password_enc'],true)?:'';if($pass==='')throw new RuntimeException('OLT password is empty.');
 $lg=api($o,'sys_login','POST',['Usrname'=>(string)$o['username'],'Password'=>md5($pass)]);$r=api($o,$module,$method,$p);try{api($o,'sys_logout','POST',[]);}catch(Throwable $x){}return['login'=>$lg,'data'=>$r];
}
$u=login();$id=(int)($_GET['olt']??$_POST['olt']??0);$q=$db->prepare('SELECT * FROM olts WHERE id=? AND active=1');$q->execute([$id]);$o=$q->fetch();if(!$o){http_response_code(404);exit('OLT not found');}
if($u['role']!=='super_admin'){ $q=$db->prepare("SELECT 1 FROM resource_permissions WHERE reseller_id=? AND resource_type='olt' AND resource_id=? AND can_view=1");$q->execute([$u['id'],$id]);if(!$q->fetchColumn()){http_response_code(403);exit('Forbidden');}}
$mods=['onu_list_get'=>'GET','onu_info_detail'=>'GET','sys_ddm_info'=>'GET','port_ddm_status_get'=>'GET','sys_onu_brief'=>'GET','ont_optical_list_get'=>'GET','ont_optical_get'=>'GET','onu_reboot'=>'POST'];$out=null;$err='';$sel=(string)($_POST['module']??'');$params=(string)($_POST['params']??'');
if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Invalid CSRF');}try{$p=$params===''?[]:json_decode($params,true,512,JSON_THROW_ON_ERROR);if(!is_array($p))throw new RuntimeException('Parameters must be a JSON object.');if($sel==='onu_reboot'&&$u['role']!=='super_admin')throw new RuntimeException('Reboot requires admin permission.');$out=call($o,$sel,$mods[$sel]??'GET',$p);}catch(Throwable $x){$err=$x->getMessage();}}
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));
?><!doctype html><html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ECOM CGI API</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><style>body{background:#f4f6fa}.card{border:0;box-shadow:0 2px 12px #0001}.mono{font:12px ui-monospace,monospace;white-space:pre-wrap;word-break:break-word}</style></head><body><div class="container py-4"><a href="index.php?page=olts">← ECOM OLT</a><h2 class="mt-2"><?=e($o['name'])?></h2><?php if($err):?><div class="alert alert-danger"><?=e($err)?></div><?php endif;?><div class="card p-4"><h5>ECOM CGI API</h5><p class="text-muted small">Base: <?=e(($o['web_scheme']??'http').'://'.$o['host'].':'.($o['web_port']??9092))?>/cgi-bin/h.cgi?module=MODULE_NAME</p><form method="post"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><input type="hidden" name="olt" value="<?=$id?>"><div class="row g-2"><div class="col-md-5"><select name="module" class="form-select" required><option value="">Select module</option><?php foreach($mods as $m=>$method):?><option value="<?=e($m)?>" <?=$sel===$m?'selected':''?>><?=e($m)?> — <?=e($method)?></option><?php endforeach;?></select></div><div class="col-md-7"><input name="params" class="form-control mono" placeholder='GET/POST parameters JSON, e.g. {"PonId":1,"OnuId":1}' value="<?=e($params)?>"></div></div><button class="btn btn-primary mt-3">Run CGI API</button></form></div><?php if($out):?><div class="card p-4 mt-3"><h5>Response</h5><div>Login HTTP: <?=e($out['login']['http'])?> · API HTTP: <?=e($out['data']['http'])?></div><pre class="mono mt-2"><?=e(json_encode($out['data']['json']??$out['data']['raw'],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></pre></div><?php endif;?></div></body></html>
